# This workflow is disabled.

name: Oncall Triage

on: [push]  # Add more events if necessary

jobs:
  disable:
    runs-on: ubuntu-latest
    steps:
      - name: Disable this workflow
        run: echo 'Workflow is disabled.'